---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: centos6
    driver:
      box: C:/learningchef/centos65-1.0.6.box
      network:
        - ["private_network", {ip: "192.168.33.7"}]

suites:
  - name: apache
    run_list:
      - recipe[apache::default]
    attributes:

